FROM ubuntu:18.04

## supress interactive dialogs
ARG DEBIAN_FRONTEND=noninteractive


## install OS dependencies
RUN apt-get update
RUN apt-get install software-properties-common openslide-tools python-openslide default-jre git vim curl tree -y
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get install python3.9 python3-pip -y


## create user so python packages are not being installed with root and jupyter is not executed with root
RUN groupadd laluna
RUN useradd -rm -d /home/laluna -s /bin/bash -g laluna -u 1001 laluna
USER laluna
WORKDIR /home/laluna
ENV PATH=$PATH:/home/laluna/.local/bin

## install luna
RUN python3 -m pip install --no-cache-dir --user --upgrade pip
RUN pip install pyluna
RUN pip install pyluna-pathology
RUN pip uninstall -y pyspark ## temp hack for getting pyspark v3.1.2 to play well with deltalake
RUN pip install pyspark==3.1.2

## install jupyter
RUN python3 -m pip install --no-cache-dir jupyter

## copy tutorial files
RUN mkdir -p classifier img luna/conf notebooks
ADD classifier /home/laluna/classifier/
ADD conf /home/laluna/luna/conf/
ADD img /home/laluna/img/
ADD notebooks /home/laluna/notebooks
USER root
RUN chown -R laluna:laluna /home/laluna/
RUN rm -f /home/laluna/*.bk
USER laluna

## set env vars
ENV LUNA_HOME="/home/laluna/luna"
# pyspark adds /bin/java
ENV JAVA_HOME="/usr"
ENV LANG="C.UTF-8"
ENV PYSPARK_PYTHON="/usr/bin/python3"
ENV PYSPARK_DRIVER_PYTHON="/usr/bin/python3"


## verify installation
RUN java --version
RUN echo $JAVA_HOME
RUN echo $LUNA_HOME
RUN echo PYSPARK_PYTHON
RUN echo PYSPARK_DRIVER_PYTHON
RUN which jupyter
RUN pip list | grep luna
RUN python3 -c 'import luna'


## entrypoint
CMD jupyter notebook --ip 0.0.0.0 --notebook-dir=/home/laluna/notebooks


