FROM ubuntu:18.04

## supress interactive dialogs
ARG DEBIAN_FRONTEND=noninteractive


## install OS dependencies
RUN apt update
RUN apt install software-properties-common openslide-tools python-openslide default-jre git vim curl tree -y
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt install python3.9 python3-pip -y


## create user so python packages are not being installed with root and jupyter is not executed with root
RUN groupadd laluna
RUN useradd -rm -d /home/laluna -s /bin/bash -g laluna -u 1001 laluna
USER laluna
WORKDIR /home/laluna
ENV PATH=$PATH:/home/laluna/.local/bin


## install luna
RUN python3 -m pip install --no-cache-dir --user --upgrade pip setuptools wheel
RUN git clone https://github.com/msk-mind/luna.git
WORKDIR /home/laluna/luna
RUN sed -i 's/pyluna-core/pyluna-core\ @\ file:\/\/localhost\/home\/laluna\/luna\/pyluna-core/g' setup.cfg
RUN sed -i 's/pyluna-common/pyluna-common\ @\ file:\/\/localhost\/home\/laluna\/luna\/pyluna-common/g' pyluna-core/setup.cfg
RUN sed -i 's/pyluna-pathology/pyluna-pathology\ @\ file:\/\/localhost\/home\/laluna\/luna\/pyluna-pathology/g' setup.cfg
RUN sed -i 's/pyluna-common/pyluna-common\ @\ file:\/\/localhost\/home\/laluna\/luna\/pyluna-common/g' pyluna-pathology/setup.cfg
RUN python3 -m pip install --no-cache-dir --use-deprecated=legacy-resolver .[pathology]


## install jupyter
RUN python3 -m pip install --no-cache-dir jupyter


## copy tutorial files
WORKDIR /home/laluna
RUN mkdir classifier configs img
ADD classifier /home/laluna/classifier/
ADD configs /home/laluna/configs/
ADD img /home/laluna/img/
ADD notebooks /home/laluna/
RUN cp luna/conf/datastore.default.yml luna/conf/datastore.cfg
USER root
RUN chown laluna:laluna /home/laluna/*.ipynb
RUN rm -f /home/laluna/*.bk
USER laluna

## set env vars
ENV LUNA_HOME="/home/laluna/luna"
# pyspark adds /bin/java
ENV JAVA_HOME="/usr"
ENV LANG="C.UTF-8"
ENV PYSPARK_PYTHON="/usr/bin/python3"
ENV PYSPARK_DRIVER_PYTHON="/usr/bin/python3"


## verify installation
RUN java --version
RUN echo $JAVA_HOME
RUN echo $LUNA_HOME
RUN echo PYSPARK_PYTHON
RUN echo PYSPARK_DRIVER_PYTHON
RUN which jupyter
RUN pip list | grep luna
RUN python3 -c 'import luna'


## entrypoint
CMD jupyter notebook --ip 0.0.0.0 --notebook-dir=/home/laluna


