# docker-compose.yml
version: '3'
services:
  star_dist:
    image: docker.io/druvpatel/qupath-stardist
    user: $UID:$GID
    working_dir: $PWD
    stdin_open: true
    volumes:
      - $PWD/data:/data
      - $PWD/models:/models
      - $PWD/scripts:/scripts
      - $PWD/detections:/detections 
    tty: true
