
# https://hub.docker.com/r/adoptopenjdk/openjdk16
FROM adoptopenjdk/openjdk16:x86_64-debian-jdk-16.0.1_9
MAINTAINER MSK-MIND
LABEL "app"="qupath"
LABEL "version"="0.3.1"
LABEL "description"="qupath bundled with stardist and tensorflow for CPUs. Change -Ptensorflow-cpu=false to switch to GPUs"
RUN apt-get update && \
    apt-get install -y sudo tree wget git vim  && \
    apt-get install -y gnupg2 && \
    apt-get install -y binutils  && \
    apt-get install -y libxml2-dev libtiff-dev libglib2.0-0 libxcb-shm0-dev libxrender-dev libxcb-render0-dev && \
    apt-get install -y libgl1-mesa-glx && \
    apt-get install -y software-properties-common

# build qupath (latest)
RUN /bin/sh -c cd / && mkdir qupath &&    \
        git clone --branch v0.3.1 https://github.com/qupath/qupath.git /qupath &&   \
        cd /qupath &&   \
        ./gradlew clean build -x test jpackage -Dhttp.socketTimeout=60000 -Dhttp.connectionTimeout=60000


# build qupath-stardist extension
RUN /bin/sh -c cd / && mkdir qupath-stardist &&    \
        git clone --branch v0.3.0 https://github.com/qupath/qupath-extension-stardist.git /qupath-stardist &&   \
        cd /qupath-stardist &&   \
        ./gradlew clean build -x test -Dhttp.socketTimeout=60000 -Dhttp.connectionTimeout=60000

ARG USER_ID
ARG USER_NAME
RUN groupadd $USER_NAME
RUN useradd -l -rm -d /home/$USER_NAME -s /bin/bash -g $USER_NAME -u $USER_ID $USER_NAME
USER $USER_NAME

