# https://hub.docker.com/r/adoptopenjdk/openjdk14
FROM adoptopenjdk/openjdk14:x86_64-debian-jdk-14.0.2_12

MAINTAINER MSK-MIND

LABEL "app"="qupath"
LABEL "version"="0.2.3"
LABEL "description"="qupath bundled with stardist and tensorflow for CPUs. Change -Ptensorflow-cpu=false to switch to GPUs"


# binutils is a required dependency for jdk
# first line of lib* are required dependencies for qupath
# second line of lib* are required dependencies for stardist
# if additional libs are required, search for libs using "apt-cache search 'libname'" and add to commands below
RUN apt-get update && \
    apt-get install -y sudo tree wget git vim && \
    apt-get install -y gnupg2 && \
    apt-get install -y binutils  && \
    apt-get install -y libxml2-dev libtiff-dev libglib2.0-0 libxcb-shm0-dev libxrender-dev libxcb-render0-dev && \
    apt-get install -y libgl1-mesa-glx

# skip tests (because they are failing) and build
RUN git clone --branch v0.2.3 https://github.com/qupath/qupath.git && \
    cd qupath && \
    ./gradlew clean build createPackage -x test -Ptensorflow-cpu=true

